package bean;
// Generated 15/12/2024 23:13:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GbrProduto generated by hbm2java
 */
@Entity
@Table(name="gbr_produto"
    ,catalog="db_giovana_rodrigues"
)
public class GbrProduto  implements java.io.Serializable {


     private int gbrIdproduto;
     private String gbrNome;
     private int gbrCodBarra;
     private double gbrPreco;
     private String gbrDescricao;
     private int gbrEstoqueAtual;
     private int gbrEstoqueMax;

    public GbrProduto() {
    }

    public GbrProduto(String gbrNome, int gbrCodBarra, double gbrPreco, String gbrDescricao, int gbrEstoqueAtual, int gbrEstoqueMax) {
       this.gbrNome = gbrNome;
       this.gbrCodBarra = gbrCodBarra;
       this.gbrPreco = gbrPreco;
       this.gbrDescricao = gbrDescricao;
       this.gbrEstoqueAtual = gbrEstoqueAtual;
       this.gbrEstoqueMax = gbrEstoqueMax;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="gbr_idproduto", unique=true, nullable=false)
    public int getGbrIdproduto() {
        return this.gbrIdproduto;
    }
    
    public void setGbrIdproduto(int gbrIdproduto) {
        this.gbrIdproduto = gbrIdproduto;
    }

    
    @Column(name="gbr_nome", nullable=false, length=45)
    public String getGbrNome() {
        return this.gbrNome;
    }
    
    public void setGbrNome(String gbrNome) {
        this.gbrNome = gbrNome;
    }

    
    @Column(name="gbr_codBarra", nullable=false)
    public int getGbrCodBarra() {
        return this.gbrCodBarra;
    }
    
    public void setGbrCodBarra(int gbrCodBarra) {
        this.gbrCodBarra = gbrCodBarra;
    }

    
    @Column(name="gbr_preco", nullable=false, precision=6)
    public double getGbrPreco() {
        return this.gbrPreco;
    }
    
    public void setGbrPreco(double gbrPreco) {
        this.gbrPreco = gbrPreco;
    }

    
    @Column(name="gbr_descricao", nullable=false, length=150)
    public String getGbrDescricao() {
        return this.gbrDescricao;
    }
    
    public void setGbrDescricao(String gbrDescricao) {
        this.gbrDescricao = gbrDescricao;
    }

    
    @Column(name="gbr_estoqueAtual", nullable=false)
    public int getGbrEstoqueAtual() {
        return this.gbrEstoqueAtual;
    }
    
    public void setGbrEstoqueAtual(int gbrEstoqueAtual) {
        this.gbrEstoqueAtual = gbrEstoqueAtual;
    }

    
    @Column(name="gbr_estoqueMax", nullable=false)
    public int getGbrEstoqueMax() {
        return this.gbrEstoqueMax;
    }
    
    public void setGbrEstoqueMax(int gbrEstoqueMax) {
        this.gbrEstoqueMax = gbrEstoqueMax;
    }




}


