package bean;
// Generated 15/12/2024 23:13:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GbrPedidosProdutos generated by hbm2java
 */
@Entity
@Table(name="gbr_pedidos_produtos"
    ,catalog="db_giovana_rodrigues"
)
public class GbrPedidosProdutos  implements java.io.Serializable {


     private int gbrIdPedidosProdutos;
     private int gbrPedido;
     private int gbrProdutos;
     private int gbrQuantidade;

    public GbrPedidosProdutos() {
    }

    public GbrPedidosProdutos(int gbrIdPedidosProdutos, int gbrPedido, int gbrProdutos, int gbrQuantidade) {
       this.gbrIdPedidosProdutos = gbrIdPedidosProdutos;
       this.gbrPedido = gbrPedido;
       this.gbrProdutos = gbrProdutos;
       this.gbrQuantidade = gbrQuantidade;
    }
   
     @Id 

    
    @Column(name="gbr_idPedidos_produtos", unique=true, nullable=false)
    public int getGbrIdPedidosProdutos() {
        return this.gbrIdPedidosProdutos;
    }
    
    public void setGbrIdPedidosProdutos(int gbrIdPedidosProdutos) {
        this.gbrIdPedidosProdutos = gbrIdPedidosProdutos;
    }

    
    @Column(name="gbr_pedido", nullable=false)
    public int getGbrPedido() {
        return this.gbrPedido;
    }
    
    public void setGbrPedido(int gbrPedido) {
        this.gbrPedido = gbrPedido;
    }

    
    @Column(name="gbr_produtos", nullable=false)
    public int getGbrProdutos() {
        return this.gbrProdutos;
    }
    
    public void setGbrProdutos(int gbrProdutos) {
        this.gbrProdutos = gbrProdutos;
    }

    
    @Column(name="gbr_quantidade", nullable=false)
    public int getGbrQuantidade() {
        return this.gbrQuantidade;
    }
    
    public void setGbrQuantidade(int gbrQuantidade) {
        this.gbrQuantidade = gbrQuantidade;
    }




}


