package bean;
// Generated 12/01/2025 02:09:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GbrUsuario generated by hbm2java
 */
@Entity
@Table(name="gbr_usuario"
    ,catalog="db_giovana_rodrigues"
)
public class GbrUsuario  implements java.io.Serializable {


     private int idgbrUsuario;
     private String gbrNome;
     private String gbrApelido;
     private String gbrCpf;
     private Date gbrDataNasc;
     private String gbrEmail;
     private String gbrLogin;
     private String gbrSenha;
     private char gbrAdministrador;
     private String gbrSituacao;

    public GbrUsuario() {
    }

    public GbrUsuario(String gbrNome, String gbrApelido, String gbrCpf, Date gbrDataNasc, String gbrEmail, String gbrLogin, String gbrSenha, char gbrAdministrador, String gbrSituacao) {
       this.gbrNome = gbrNome;
       this.gbrApelido = gbrApelido;
       this.gbrCpf = gbrCpf;
       this.gbrDataNasc = gbrDataNasc;
       this.gbrEmail = gbrEmail;
       this.gbrLogin = gbrLogin;
       this.gbrSenha = gbrSenha;
       this.gbrAdministrador = gbrAdministrador;
       this.gbrSituacao = gbrSituacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idgbr_usuario", unique=true, nullable=false)
    public int getIdgbrUsuario() {
        return this.idgbrUsuario;
    }
    
    public void setIdgbrUsuario(int idgbrUsuario) {
        this.idgbrUsuario = idgbrUsuario;
    }

    
    @Column(name="gbr_nome", nullable=false, length=50)
    public String getGbrNome() {
        return this.gbrNome;
    }
    
    public void setGbrNome(String gbrNome) {
        this.gbrNome = gbrNome;
    }

    
    @Column(name="gbr_apelido", nullable=false, length=15)
    public String getGbrApelido() {
        return this.gbrApelido;
    }
    
    public void setGbrApelido(String gbrApelido) {
        this.gbrApelido = gbrApelido;
    }

    
    @Column(name="gbr_cpf", nullable=false, length=11)
    public String getGbrCpf() {
        return this.gbrCpf;
    }
    
    public void setGbrCpf(String gbrCpf) {
        this.gbrCpf = gbrCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gbr_dataNasc", nullable=false, length=10)
    public Date getGbrDataNasc() {
        return this.gbrDataNasc;
    }
    
    public void setGbrDataNasc(Date gbrDataNasc) {
        this.gbrDataNasc = gbrDataNasc;
    }

    
    @Column(name="gbr_email", nullable=false, length=50)
    public String getGbrEmail() {
        return this.gbrEmail;
    }
    
    public void setGbrEmail(String gbrEmail) {
        this.gbrEmail = gbrEmail;
    }

    
    @Column(name="gbr_login", nullable=false, length=45)
    public String getGbrLogin() {
        return this.gbrLogin;
    }
    
    public void setGbrLogin(String gbrLogin) {
        this.gbrLogin = gbrLogin;
    }

    
    @Column(name="gbr_senha", nullable=false, length=20)
    public String getGbrSenha() {
        return this.gbrSenha;
    }
    
    public void setGbrSenha(String gbrSenha) {
        this.gbrSenha = gbrSenha;
    }

    
    @Column(name="gbr_administrador", nullable=false, length=1)
    public char getGbrAdministrador() {
        return this.gbrAdministrador;
    }
    
    public void setGbrAdministrador(char gbrAdministrador) {
        this.gbrAdministrador = gbrAdministrador;
    }

    
    @Column(name="gbr_situacao", nullable=false, length=10)
    public String getGbrSituacao() {
        return this.gbrSituacao;
    }
    
    public void setGbrSituacao(String gbrSituacao) {
        this.gbrSituacao = gbrSituacao;
    }




}


