package bean;
// Generated 15/12/2024 23:13:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subgrupo generated by hbm2java
 */
@Entity
@Table(name="subgrupo"
    ,catalog="db_giovana_rodrigues"
)
public class Subgrupo  implements java.io.Serializable {


     private int idsubgrupo;
     private int grupo;
     private String descricao;
     private double valor;

    public Subgrupo() {
    }

	
    public Subgrupo(int idsubgrupo) {
        this.idsubgrupo = idsubgrupo;
    }
    public Subgrupo(int idsubgrupo, int grupo, String descricao, double valor) {
       this.idsubgrupo = idsubgrupo;
       this.grupo = grupo;
       this.descricao = descricao;
       this.valor = valor;
    }
   
     @Id 

    
    @Column(name="idsubgrupo", unique=true, nullable=false)
    public int getIdsubgrupo() {
        return this.idsubgrupo;
    }
    
    public void setIdsubgrupo(int idsubgrupo) {
        this.idsubgrupo = idsubgrupo;
    }

    
    @Column(name="grupo")
    public int getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(int grupo) {
        this.grupo = grupo;
    }

    
    @Column(name="descricao", length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="valor", precision=10, scale=5)
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }




}


