package bean;
// Generated 12/01/2025 01:56:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subgrupo generated by hbm2java
 */
@Entity
@Table(name="subgrupo"
    ,catalog="db_giovana_rodrigues"
)
public class Subgrupo  implements java.io.Serializable {


     private int idsubgrupo;
     private Integer grupo;
     private String descricao;
     private BigDecimal valor;

    public Subgrupo() {
    }

	
    public Subgrupo(int idsubgrupo) {
        this.idsubgrupo = idsubgrupo;
    }
    public Subgrupo(int idsubgrupo, Integer grupo, String descricao, BigDecimal valor) {
       this.idsubgrupo = idsubgrupo;
       this.grupo = grupo;
       this.descricao = descricao;
       this.valor = valor;
    }
   
     @Id 

    
    @Column(name="idsubgrupo", unique=true, nullable=false)
    public int getIdsubgrupo() {
        return this.idsubgrupo;
    }
    
    public void setIdsubgrupo(int idsubgrupo) {
        this.idsubgrupo = idsubgrupo;
    }

    
    @Column(name="grupo")
    public Integer getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Integer grupo) {
        this.grupo = grupo;
    }

    
    @Column(name="descricao", length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="valor", precision=10, scale=5)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


